CREATE TABLE "CRADMIN"."WS_FCSTAFF" (
    "NETID"            VARCHAR2(50 BYTE),
    "AUDIT_TIMESTAMP"  TIMESTAMP(6),
    "HOSTNAME"         VARCHAR2(50 BYTE),
    "TERMINATIONDATE"  DATE,
    "ISADMIN"          NUMBER DEFAULT 0,
    "APPLICATION"      VARCHAR2(10 BYTE),
    "ROLE"             VARCHAR2(20 BYTE),
    "DEPT_ID"          VARCHAR2(20 BYTE)
)
SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
    STORAGE ( INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL
    DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT )
TABLESPACE "CAMPUSRES";

CREATE UNIQUE INDEX "CRADMIN"."NETID_INDEX" ON
    "CRADMIN"."WS_FCSTAFF" (
        "APPLICATION",
        "NETID"
    )
        PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
            STORAGE ( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL
            DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT )
        TABLESPACE "CAMPUSRES";