CREATE TABLE "CRADMIN"."WS_FCIDASSOCNAME" (
    "FIRSTNAME"    VARCHAR2(40 BYTE),
    "LASTNAME"     VARCHAR2(40 BYTE),
    "APPLICATION"  VARCHAR2(2 BYTE)
        NOT NULL ENABLE,
    "SBUID"        VARCHAR2(40 BYTE),
    CONSTRAINT "WS_FCIDASSOCNAME_PRIMARY" PRIMARY KEY ( "SBUID",
                                                        "APPLICATION" )
        USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
            STORAGE ( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL
            DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT )
        TABLESPACE "CAMPUSRES"
    ENABLE
)
SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
    STORAGE ( INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL
    DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT )
TABLESPACE "CAMPUSRES";