CREATE TABLE "CRADMIN"."WS_FCSWIPES" (
    "SBUID"           NUMBER,
    "SWIPE_TIME_IN"   TIMESTAMP(6),
    "HOSTNAME_IN"     VARCHAR2(50 BYTE),
    "FIRSTNAME"       VARCHAR2(80 BYTE),
    "LASTNAME"        VARCHAR2(80 BYTE),
    "IP_IN"           VARCHAR2(40 BYTE),
    "HOSTNAME_OUT"    VARCHAR2(50 BYTE),
    "SWIPE_TIME_OUT"  TIMESTAMP(6),
    "IP_OUT"          VARCHAR2(40 BYTE),
    "NETID_IN"        VARCHAR2(50 BYTE),
    "NETID_OUT"       VARCHAR2(50 BYTE),
    "APPLICATION"     VARCHAR2(2 BYTE)
)
SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
    STORAGE ( INITIAL 786432 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL
    DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT )
TABLESPACE "CAMPUSRES";

CREATE INDEX "CRADMIN"."APP_SBUID_SWIPETIME_INDEX" ON
    "CRADMIN"."WS_FCSWIPES" (
        "APPLICATION"
    DESC,
        "SBUID"
    DESC,
        "SWIPE_TIME_IN"
    DESC )
        PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
            STORAGE ( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL
            DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT )
        TABLESPACE "CAMPUSRES";