CREATE TABLE "CRADMIN"."WS_FCSTAFFWORKLOG" (
    "NETID"               VARCHAR2(50 BYTE),
    "CHECKIN_TIMESTAMP"   TIMESTAMP(6),
    "CHECKOUT_TIMESTAMP"  TIMESTAMP(6),
    "CHECKIN_HOSTNAME"    VARCHAR2(50 BYTE),
    "CHECKOUT_HOSTNAME"   VARCHAR2(50 BYTE),
    "APPLICATION"         VARCHAR2(10 BYTE),
    "CHECKIN_IP"          VARCHAR2(15 BYTE),
    "CHECKOUT_IP"         VARCHAR2(15 BYTE),
    "DEPARTMENT_ID"       VARCHAR2(10 BYTE)
)
SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
    STORAGE ( INITIAL 917504 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL
    DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT )
TABLESPACE "CAMPUSRES";

CREATE INDEX "CRADMIN"."INDEX1" ON
    "CRADMIN"."WS_FCSTAFFWORKLOG" (
        "NETID",
        "APPLICATION",
        "CHECKIN_TIMESTAMP"
    )
        PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
            STORAGE ( INITIAL 524288 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL
            DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT )
        TABLESPACE "CAMPUSRES";