CREATE TABLE "CRADMIN"."WS_FCVISITS" (
    "SBUID"            NUMBER,
    "SWIPETIME"        TIMESTAMP(6),
    "HOSTNAME"         VARCHAR2(50 BYTE),
    "FIRSTNAME"        VARCHAR2(80 BYTE),
    "LASTNAME"         VARCHAR2(80 BYTE),
    "LOCATION"         VARCHAR2(80 BYTE),
    "IP"               VARCHAR2(40 BYTE),
    "NOTE"             VARCHAR2(500 BYTE),
    "NETID_AUDIT"      VARCHAR2(20 BYTE),
    "APPLICATION_BAK"  VARCHAR2(10 BYTE),
    "APPLICATION"      VARCHAR2(10 BYTE)
)
SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
    STORAGE ( INITIAL 11534336 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL
    DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT )
TABLESPACE "CAMPUSRES";

CREATE INDEX "CRADMIN"."SWIPETIME_INDEX" ON
    "CRADMIN"."WS_FCVISITS" (
        "SWIPETIME"
    DESC )
        PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
            STORAGE ( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL
            DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT )
        TABLESPACE "CAMPUSRES";

CREATE INDEX "CRADMIN"."WS_FCVISITS_APP_LOC_TIME_IDX" ON
    "CRADMIN"."WS_FCVISITS" (
        "APPLICATION",
        "LOCATION",
        "SWIPETIME"
    DESC )
        PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
            STORAGE ( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL
            DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT )
        TABLESPACE "CAMPUSRES";

CREATE INDEX "CRADMIN"."WS_FCVISITS_APP_NETID_TIME_IDX" ON
    "CRADMIN"."WS_FCVISITS" (
        "APPLICATION",
        "NETID_AUDIT",
        "SWIPETIME"
    DESC )
        PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
            STORAGE ( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL
            DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT )
        TABLESPACE "CAMPUSRES";

CREATE INDEX "CRADMIN"."WS_FCVISITS_APP_TIME_IDX" ON
    "CRADMIN"."WS_FCVISITS" (
        "APPLICATION",
        "SWIPETIME"
    DESC )
        PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
            STORAGE ( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL
            DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT )
        TABLESPACE "CAMPUSRES";