CREATE TABLE CRADMIN.WS_FCSTAFFWORKLOG (
    NETID              VARCHAR2(50),
    CHECKIN_TIMESTAMP  TIMESTAMP(6),
    CHECKOUT_TIMESTAMP TIMESTAMP(6),
    CHECKIN_HOSTNAME   VARCHAR2(50),
    CHECKOUT_HOSTNAME  VARCHAR2(50),
    APPLICATION        VARCHAR2(10),
    CHECKIN_IP         VARCHAR2(15),
    CHECKOUT_IP        VARCHAR2(15),
    DEPARTMENT_ID      VARCHAR2(10),
    SHIFT_CATEGORY_ID  NUMBER,
    CONSTRAINT FK_WORKLOG_SHIFT_CAT
        FOREIGN KEY (SHIFT_CATEGORY_ID)
        REFERENCES CRADMIN.WS_CR_CS_SHIFT_CATEGORIES (ID)
)
TABLESPACE CAMPUSRES;

CREATE INDEX CRADMIN.INDEX1
    ON CRADMIN.WS_FCSTAFFWORKLOG (NETID, APPLICATION, CHECKIN_TIMESTAMP)
    TABLESPACE CAMPUSRES;