CREATE TABLE "CRADMIN"."WS_FC_DEPARTMENTS" (
    "APPLICATION"  VARCHAR2(2 BYTE),
    "NAME"         VARCHAR2(40 BYTE),
    "DEPT_ID"      NUMBER(10, 0),
    "INACTIVE"     NUMBER(1, 0)
)
SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
    STORAGE ( INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL
    DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT )
TABLESPACE "CAMPUSRES";